### ISSUE TITLE
did it work ?

### ISSUE THREAD

**Issue by jagdishjadeja** [tmacdou4/2019-nCov#1]
did it work ?
on actual corona virus effected patient ?

**Comment by tmacdou4** [comment]
Many more steps are needed for anything here to be actually tested on a patient. For the generated compounds, a synthesis plan needs to be made for how to make the compound. Then, interesting compounds need to be synthesized before they can be tested, which also takes time. Only then can the compounds actually be tested in an assay, then tested for toxicity, then used in animal models, then used in human clinical trials. A huge process!

**Comment by jagdishjadeja** [comment]
That's really disappointing.
Can't you take same dna of animal and try on its dna code?

**Comment by tmacdou4** [comment]
I'm not quite sure what you mean by that, but unfortunately I believe this is about as far as the testing can go without the efforts of a wet lab.
